name: Semantic Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # CI jobs that must succeed before release
  ci:
    name: Run CI
    uses: ./.github/workflows/ci.yml

  release:
    runs-on: ubuntu-latest
    needs: ci
    concurrency: release
    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.7.12"

      - name: Set up Python
        run: uv python install 3.12

      - name: Install dependencies
        run: |
          uv sync --dev
          uv pip install python-semantic-release build

      - name: Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          echo "Running semantic-release with verbose output..."
          # 公式Actionの設定パターンを参考にしたエラーハンドリング
          if ! uv run semantic-release --verbose version; then
            echo "Version update failed, checking if it's because no changes detected..."
            exit_code=$?
            if [ $exit_code -eq 2 ]; then
              echo "No release necessary"
              exit 0
            else
              exit $exit_code
            fi
          fi
